#!/bin/bash

STAMP=$(date +%Y%m%d_%H%M%S)
source ~/.basepi/sendemail.conf
HOSTNAME=$(hostname)
MYIP=$(ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p')
MSGFILE=/tmp/emailbody
ME=$(whoami)
SCRIPTFILE=$(basename "$0")
SUBJECT="BasePi Update: "$HOSTNAME

avalue=""

while getopts 'lha:' OPTION; do
  case "$OPTION" in
    l) echo "linuxconfig";;
    h) echo "h stands for h";;
    a) avalue="$OPTARG"; echo "The value provided is $OPTARG";;
    ?)
      echo "script usage: $(basename $0) [-l] [-h] [-a somevalue]" >&2
      exit 1
      ;;
  esac
done
shift "$(($OPTIND -1))"

echo "Email generated by "$SCRIPTFILE" on "$HOSTNAME" by "$ME > $MSGFILE
echo `date` >> $MSGFILE
echo "RPi System: "$HOSTNAME >> $MSGFILE
echo "My IP Address: "$MYIP >> $MSGFILE
echo ""

cd ~/basepi
git reset --hard origin/master
echo "Get updated package =========================================" >> $MSGFILE
git pull >> $MSGFILE
echo "Install updates =============================================" >> $MSGFILE
sh install.sh >> $MSGFILE

sendemail -f $FROM -t $TO -u $SUBJECT -o message-file=$MSGFILE -s $SERVER -xu $USER -xp $PASS -o tls=auto -v

rm -f $MSGFILE