#!/bin/bash

STAMP=$(date +%Y%m%d_%H%M%S)
source ~/.basepi/sendemail.conf
HOSTNAME=$(hostname)
MYIP=$(ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p')
MSGFILE=/tmp/emailbody
ME=$(whoami)
SCRIPTFILE=$(basename "$0")
SUBJECT="BasePi Update: "$HOSTNAME

CURVERSION=$(curl -s https://raw.githubusercontent.com/lxcreations/basepi/master/version)
INSVERSION=~/.baseip/version

if [ "$CURVERSION" -gt "$INSVERSION" ]; then
    echo "A new version of BasePi is available"
fi

echo "Email generated by "$SCRIPTFILE" on "$HOSTNAME" by "$ME > $MSGFILE
echo `date` >> $MSGFILE
echo "RPi System: "$HOSTNAME >> $MSGFILE
echo "My IP Address: "$MYIP >> $MSGFILE
echo 


cd ~/basepi
git reset --hard origin/master
echo "Get updated package =========================================" >> $MSGFILE
git pull >> $MSGFILE
echo "Install updates =============================================" >> $MSGFILE
sh install.sh >> $MSGFILE

sendemail -f $FROM -t $TO -u $SUBJECT -o message-file=$MSGFILE -s $SERVER -xu $USER -xp $PASS -o tls=auto -v

rm -f $MSGFILE