#!/bin/bash

STAMP=$(date +%Y%m%d_%H%M%S)
source ~/.basepi/sendemail.conf
source ~/.basepi/update.conf
HOSTNAME=$(hostname)
MYIP=$(ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p')
MSGFILE=/tmp/emailbody
ME=$(whoami)
SCRIPTFILE=$(basename "$0")
SUBJECT="BasePi Update: "$HOSTNAME

CURVERSION=$(curl -s https://raw.githubusercontent.com/lxcreations/basepi/master/version)
INSVERSION=$(cat ~/.basepi/version)

 if (($CURVERSION <= $INSVERSION )); then
	echo `date`
	echo "No Updates"
	exit 0
fi

echo "Email generated by "$SCRIPTFILE" on "$HOSTNAME" by "$ME > $MSGFILE
echo `date` >> $MSGFILE
echo "RPi System: "$HOSTNAME >> $MSGFILE
echo "My IP Address: "$MYIP >> $MSGFILE
echo
echo "BasePi version $CURVERSION is now available." >> $MSGFILE

cd /tmp
git clone https://github.com/lxcreations/basepi.git
cd /tmp/basepi

#include the baspi config file
source /tmp/basepi/config/basepi.conf

for file in $(find /tmp/basepi/. -maxdepth 1 -name ".*" -type f  -printf "%f\n" ); do
	cp -uv /tmp/basepi/$file $INSTALLDIR/$INSTALLDOTS;
done

for sfile in $(find /tmp/basepi/scripts/ -maxdepth 1 -name "*" -type f  -printf "%f\n" ); do
	cp -uv /tmp/basepi/scripts/$sfile $INSTALLDIR/$INSTALLSCRIPTS
done

cp -uv /tmp/basepi/version $INSTALLDIR

rm -rf /tmp/basepi

echo "Update complete." >> $MSGFILE
echo "For the latet release notes, view the readme page at https://github.com/lxcreations/basepi." >> $MSGFILE

sendemail -f $FROM -t $TO -u $SUBJECT -o message-file=$MSGFILE -s $SERVER -xu $USER -xp $PASS -o tls=auto -v

rm -f $MSGFILE